### ISSUE TITLE
Reactわからん

### ISSUE THREAD

**Issue by isshun226** [ISC-MakeIT/Notece_v2#15]
完全理解してくれ

**Comment by isshun226** [comment]
ここに毎日進捗書いてね❤

**Comment by ko-chin0108** [comment]
一章やった（

**Comment by isshun226** [comment]
偉い

**Comment by 56miyano** [comment]
三章まで終わりました

**Comment by isshun226** [comment]
じゃあ早く終わった方に昼飯奢るわ　がんばえぷいきゅあ～❤
@ko-chin0108 @56miyano

**Comment by DuGlaser** [comment]
最後のReduxについての章は難しいのでやらなくて大丈夫です！なにか困ったことがあったら行ってくださいね！

**Comment by ko-chin0108** [comment]
かしこまりました。ありがとう；；今日は2章やった・・・・（　＾ω＾）・・・進まん

**Comment by 56miyano** [comment]
五章まで終わりました

**Comment by ko-chin0108** [comment]
4章途中、今日はバイトあるのでここまで（　＾ω＾）・・・

**Comment by 56miyano** [comment]
7章まで終わりました

**Comment by DuGlaser** [comment]
9章まで終わったら声かけてください！タスク振ります

**Comment by 56miyano** [comment]
9章まで終わりました

**Comment by ko-chin0108** [comment]
今７章今日中におわらせましゅ；；

**Comment by DuGlaser** [comment]
了解しました。５６君に関しては今日中にタスクをふりたいと考えているので宜しくお願いします。

**Comment by ko-chin0108** [comment]
おわりました
